// Committed asset-module declarations (CI fix).
//
// next-env.d.ts (which provides next/image-types/global) is gitignored and only
// generated by `next dev`/`next build`, so a fresh checkout (CI) has no SVG/PNG
// module declarations and `tsc --noEmit` fails with TS2307 on every static
// asset import. These explicit declarations make typecheck hermetic — they
// agree with next/image-types (default string export = resolved asset URL,
// which is how all current imports use them, e.g. <Image src={GearIcon} />).

declare module '*.svg' {
  const content: string;
  export default content;
}

declare module '*.png' {
  const content: string;
  export default content;
}

declare module '*.jpg' {
  const content: string;
  export default content;
}

declare module '*.jpeg' {
  const content: string;
  export default content;
}

declare module '*.webp' {
  const content: string;
  export default content;
}
